"""Generate binary32 DCT constants with standard double-precision math only."""
import argparse
import math
import struct
from pathlib import Path

SIZES = (2, 4, 6, 8, 12, 16, 24, 32, 48, 64, 128)

def literal(value):
    return struct.unpack("f", struct.pack("f", value))[0].hex() + "f"

def cosine(n, j):
    j %= 4 * n
    if j % n == 0:
        return (1.0, 0.0, -1.0, 0.0)[j // n]
    return math.cos(math.pi * j / (2 * n))

def generate():
    lines = ["// Generated by tests/core/generate_dct_constants.py; do not edit.",
             "// Binary32 constants rounded from standard double-precision math.",
             "#pragma once", "#include <stdexcept>", "namespace neo_mv::dct_detail {"]
    for n in SIZES:
        lines.append(f"inline constexpr float cosine_{n}[] = {{")
        values = [literal(cosine(n, j)) for j in range(4*n)]
        for i in range(0, len(values), 4):
            lines.append("  " + ", ".join(values[i:i+4]) + ",")
        lines.append("};")
    for norm in (False, True):
        name = "matrix8_normalized" if norm else "matrix8"
        lines.append(f"inline constexpr float {name}[8][4] = {{")
        for k in range(8):
            values = [cosine(8, (2*x+1)*k) * (2*math.sqrt(2)/64 if norm else 1) for x in range(4)]
            lines.append("  {" + ", ".join(map(literal, values)) + "},")
        lines.append("};")
    lines += ["inline const float* cosine_table(int n) {", "  switch (n) {"]
    for n in SIZES:
        lines.append(f"  case {n}: return cosine_{n};")
    lines += ['  default: throw std::invalid_argument("unsupported DCT axis length");',
              "  }", "}", "} // namespace neo_mv::dct_detail", ""]
    return "\n".join(lines)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[2] / "src/core/motion/dct_constants.hpp"
    result = generate()
    if args.check:
        if target.read_text(encoding="utf-8") != result:
            raise SystemExit("DCT constants differ; regenerate with this script")
        print("Verified binary32 DCT constants")
    else:
        target.write_text(result, encoding="utf-8", newline="\n")
