"""Generate DCT cosine tables using integer interval arithmetic (stdlib only).

Every emitted binary64 value is checked against a rigorous cosine enclosure.
Use --check to verify the checked-in file without changing it.
"""
import argparse
from pathlib import Path
# Research oracle: integer fixed-point interval arithmetic, no float trig.
from fractions import Fraction
from math import isqrt

BITS=128; S=1<<BITS

def ceildiv(a,b): return -((-a)//b)
def add(a,b):return a[0]+b[0],a[1]+b[1]
def neg(a):return -a[1],-a[0]
def mul(a,b):
 p=[x*y for x in a for y in b];return min(p)//S,ceildiv(max(p),S)
def divint(a,n):return a[0]//n,ceildiv(a[1],n)
def atan_bounds(q,n=100):
 # Alternating series: after n terms, remainder has next term's sign
 # and absolute value at most its magnitude.
 total=sum((Fraction((-1)**k,(2*k+1)*q**(2*k+1)) for k in range(n)),Fraction())
 next=Fraction((-1)**n,(2*n+1)*q**(2*n+1))
 return min(total,total+next),max(total,total+next)
a=atan_bounds(5);b=atan_bounds(239)
pi=(16*a[0]-4*b[1],16*a[1]-4*b[0])
pi=(int(pi[0]*S//1),ceildiv(pi[1].numerator*S,pi[1].denominator))

def cosine(n,k,x):
 e=((2*x+1)*k)%(4*n);e=min(e,4*n-e)
 angle=divint((pi[0]*e,pi[1]*e),2*n);square=mul(angle,angle)
 term=(S,S);total=term
 for j in range(1,64):
  term=divint(mul(term,square),(2*j-1)*(2*j))
  total=add(total,neg(term) if j%2 else term)
 # |angle| <= pi. The omitted alternating tail after degree126 is
 # bounded by the next term; all later magnitudes decrease.
 next=divint(mul(term,square),127*128)[1]
 return total[0]-next,total[1]+next



def generate():
    lines = ["// Generated by tests/core/generate_dct_constants.py; do not edit.",
             "// Each cosine has certified absolute error < 2^-52.",
             "#pragma once", "", "#include <stdexcept>", "",
             "namespace neo_mv::dct_detail {", ""]
    sizes = (2, 4, 6, 8, 12, 16, 24, 32, 48, 64, 128)
    for n in sizes:
        values = []
        for j in range(4 * n):
            lower, upper = cosine(n, j, 0)
            value = float(Fraction(lower + upper, 2 * S))
            represented = Fraction.from_float(value)
            error = max(abs(represented - Fraction(lower, S)), abs(represented - Fraction(upper, S)))
            if error >= Fraction(1, 2**52):
                raise ArithmeticError(f"unbounded cosine at {n=}, {j=}")
            values.append(value.hex())
        lines.append(f"inline constexpr double cosine_{n}[] = {{")
        for i in range(0, len(values), 4):
            lines.append("    " + ", ".join(values[i:i + 4]) + ",")
        lines.extend(["};", ""])
    lines.extend(["inline const double* cosine_table(int size) {", "  switch (size) {"])
    for n in sizes:
        lines.extend([f"  case {n}:", f"    return cosine_{n};"])
    lines.extend(["  default:", '    throw std::invalid_argument("unsupported DCT axis length");',
                  "  }", "}", "", "} // namespace neo_mv::dct_detail", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[2] / "src/core/motion/dct_constants.hpp"
    generated = generate()
    if args.check:
        if target.read_text(encoding="utf-8") != generated:
            raise SystemExit("DCT constants differ; regenerate with this script")
        print("Verified all 1376 cosine constants and their error bounds")
    else:
        target.write_text(generated, encoding="utf-8", newline="\n")
